version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            python -m venv venv
            . venv/bin/activate
            # Run your test suite here, for example:
            # python -m unittest discover tests

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
